#!/usr/bin/env python
import asyncio
import os
import sys
from uuid import UUID

import prefect
from prefect.runner._flow_run_executor import FlowRunExecutorContext
from prefect.runner._starter_engine import EngineCommandStarter


async def execute(flow_run_id: UUID):
    async with FlowRunExecutorContext() as ctx:
        flow_run = await ctx.client.read_flow_run(flow_run_id)
        executor = ctx.create_executor(
            flow_run,
            EngineCommandStarter(),
            resolve_flow=lambda fr: None,
        )
        await executor.submit()


def main():
    if len(sys.argv) >= 2 and sys.argv[1] == "version":
        print(prefect.__version__)
    elif len(sys.argv) >= 3 and sys.argv[1] == "flow-run" and sys.argv[2] == "execute":
        try:
            try:
                flow_run_id = UUID(sys.argv[3])
            except IndexError:
                flow_run_id = UUID(os.environ.get("PREFECT__FLOW_RUN_ID") or "")
        except ValueError:
            print(f"Error: '{flow_run_id}' is not a valid UUID.")
            sys.exit(1)

        asyncio.run(execute(flow_run_id))
    else:
        print(
            "This is a minimal Prefect CLI that only supports "
            "'prefect flow-run execute [ID]'."
        )
        print(
            "For the full Prefect CLI, please use an image with the complete "
            "Prefect installation, like `prefecthq/prefect:3-latest`."
        )
        sys.exit(1)


if __name__ == "__main__":
    main()
