#!/usr/bin/env python
import asyncio
import sys
from uuid import UUID

from prefect.runner import Runner

flow_run_id = UUID(sys.argv[1])

runner = Runner()

asyncio.run(runner.execute_flow_run(flow_run_id))
