export const pages = {
  flowRuns: '/runs',
  flowRun: (id: string) => `/flow-run/${id}`,
  flowRunRadar: (id: string) => `/flow-run/${id}/radar`,
  flows: '/flows',
  flow: (id: string) => `/flow/${id}`,
  deployments: '/deployments',
  deployment: (id: string) => `/deployment/${id}`,
  deploymentEdit: (id: string) => `/deployment/${id}/edit`,
  workQueues: '/work-queues',
  workQueue: (id: string) => `/work-queue/${id}`,
  workQueueCreate: '/work-queue/new',
  workQueueEdit: (id: string) => `/work-queue/${id}`,
  blocks: '/blocks',
  blocksCatalog: '/blocks/catalog',
  blocksCatalogView: (blockTypeSlug: string) => `/blocks/catalog/${blockTypeSlug}`,
  blocksCatalogCreate: (blockTypeSlug: string) => `/blocks/catalog/${blockTypeSlug}/create`,
  block: (id: string) => `/block/${id}`,
  blockEdit: (id: string) => `/block/${id}/edit`,
  notifications: '/notifications',
  notificationsCreate: '/notifications/new',
  notificationEdit: (id: string) => `/notifications/${id}`,
  settings: '/settings',
} as const