query Task($taskId: uuid!
  $limit: Int
  $offset: Int
  $orderBy: [task_run_order_by!]
  $heartbeat: timestamptz) {
  task_by_pk(id: $taskId) {
    id
    name
    task_runs(
      where: { flow_run: { state: { _neq: "Scheduled" } } 
      heartbeat: { _gte: $heartbeat } }
      order_by: $orderBy
      limit: $limit
      offset: $offset
    ) {
      id
      map_index
      duration
      end_time
      start_time
      state
      flow_run {
        name
        id
        }
      }
    }
}

