query FlowRunsCount(
  $taskId: uuid
  $heartbeat: timestamptz
  $state: String
) {
  task_run_aggregate(
    where: {
      task_id: { _eq: $taskId }
      heartbeat: { _gte: $heartbeat }
      flow_run: { state: { _neq: "Scheduled" } }
      state: { _eq: $state }
    }
  ) {
    aggregate {
      count
    }
  }
}
