query Flow($id: uuid!) {
  flow(where: { archived: { _eq: false }, id: { _eq: $id } }) {
    id
    name
    tasks_aggregate {
      aggregate {
        count
      }
    }
    tasks {
      id
      mapped
      name
      max_retries
      retry_delay
      trigger
      type

      upstream_edges {
        upstream_task {
          id
          name
        }
        downstream_task {
          id
          name
        }
      }
      downstream_edges {
        upstream_task {
          id
          name
        }
        downstream_task {
          id
          name
        }
      }
    }
  }
}
