import functools
import prefect


class IndexTask(prefect.Task):

    def __init__(self, index, **kwargs):
        """
        A task that takes an input and returns that input indexed
        by a specific value.

        As a convenience, this task can be generated by indexing any other task:
            task = Task(...)
            indexed_task = task[3]

        """
        self.index = index
        super().__init__(**kwargs)

    def run(self, index_task):
        return index_task[self.index]
