

import React from "react";
import createClient from "openapi-fetch";
import type { paths } from "./prefect.ts"; // generated by openapi-typescript

export const client = createClient<paths>({ baseUrl: "http://localhost:4200/api" });


// Create a context to store the client

export const ServiceContext = React.createContext(client);

// Create a hook to access the client

export function useService() {
  return React.useContext(ServiceContext);
}
