

import createClient from "openapi-fetch";
import type { paths } from "./prefect.ts"; // generated by openapi-typescript

export const QueryService = createClient<paths>({ baseUrl: "http://localhost:4200/api" });
