query Heartbeat($flowRunId: uuid!, $timestamp: timestamptz, $state: String) {
  task_run(
    limit: 10
    where: {
      flow_run_id: { _eq: $flowRunId }
      state_timestamp: { _gte: $timestamp }
      state: { _eq: $state }
    }
    order_by: { state_timestamp: desc_nulls_last }
  ) {
    id
    state
    state_message
    state_timestamp
    run_count
    duration
    task {
      id
      name
      max_retries
    }
  }
}
