query TableTaskRuns(
  $flowRunId: uuid
  $name: String
  $limit: Int
  $offset: Int
  $orderBy: [task_run_order_by!]
) {
  flow_run(where: {id: {_eq: $flowRunId}}) {
    name
    id
    task_runs (
      where: { task: { name: { _ilike: $name } } }
      order_by: $orderBy
      limit: $limit
      offset: $offset
    ) {
      duration
      end_time
      map_index
      start_time
      state
      id
      task {
        id
        name
      }
    }
  }
}
