"""
This module contains a custom hatch build hook that records the build date and git commit hash.
The information is written to a _build_info.py file in the package.
"""

import textwrap
from datetime import datetime, timezone
from subprocess import CalledProcessError, check_output
from typing import Any

from hatchling.builders.hooks.plugin.interface import BuildHookInterface


class BuildHook(BuildHookInterface):
    """
    A Hatch build hook that records the build date and git commit hash.
    The information is written to a _build_info.py file in the package.
    """

    def initialize(self, version: str, build_data: dict[str, Any]) -> None:
        """
        Initialize the build hook by gathering git and build information.

        Args:
            version: The current version being built
            build_data: Build-specific data
        """
        try:
            git_hash = check_output(["git", "rev-parse", "HEAD"]).decode().strip()
        except CalledProcessError:
            git_hash = "unknown"

        self.app.display_info(f"Git hash: {git_hash}")

        build_date = datetime.now(timezone.utc).isoformat()

        self.app.display_info(f"Build date: {build_date}")

        # Create the build info module
        build_info = textwrap.dedent(
            f"""
            # Generated by prefect/_hatch/build_info.py
            __build_date__ = "{build_date}"
            __git_commit__ = "{git_hash}"
            """
        )

        with open("src/prefect/_build_info.py", "w") as f:
            f.write(build_info)
