"""Run commands and untrusted code inside disposable, kernel-isolated sandboxes.

This module is the target of the `prefect.collections` entry point, so it imports the
shipped backends eagerly for block discovery.
"""

from __future__ import annotations

from prefect_sandbox.base import (
    Sandbox,
    SandboxBackend,
    SandboxCreationError,
    SandboxError,
    SandboxExecutionError,
    SandboxResult,
    SandboxUnavailableError,
)
from prefect_sandbox.islo import IsloSandbox
from prefect_sandbox.operations import SandboxOperation, SandboxProcess
from prefect_sandbox.sbx import SbxSandbox
from prefect_sandbox.tasks import (
    arun_in_sandbox,
    arun_python_in_sandbox,
    run_in_sandbox,
    run_python_in_sandbox,
)

try:
    from prefect_sandbox import _version

    __version__ = _version.__version__
except ImportError:  # pragma: no cover - _version.py is generated by setuptools_scm
    # Absent in a source checkout that has never been built. Reporting a `0.` dev
    # version keeps a plain `pytest` run working without pretending to be a release.
    __version__ = "0.0.0.dev0"

__all__ = [
    "IsloSandbox",
    "Sandbox",
    "SandboxBackend",
    "SandboxCreationError",
    "SandboxError",
    "SandboxExecutionError",
    "SandboxOperation",
    "SandboxProcess",
    "SandboxResult",
    "SandboxUnavailableError",
    "SbxSandbox",
    "__version__",
    "arun_in_sandbox",
    "arun_python_in_sandbox",
    "run_in_sandbox",
    "run_python_in_sandbox",
]
