"""add_submission_count_to_flow_run

Revision ID: eb150e4749db
Revises: 9e83011d1f2a
Create Date: 2025-10-13 14:34:39.623614

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "eb150e4749db"
down_revision = "9e83011d1f2a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "flow_run",
        sa.Column("submission_count", sa.Integer(), server_default="0", nullable=False),
    )
    op.add_column(
        "task_run",
        sa.Column("submission_count", sa.Integer(), server_default="0", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("task_run", "submission_count")
    op.drop_column("flow_run", "submission_count")
    # ### end Alembic commands ###
