/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Prefect Prefect REST API
 * OpenAPI spec version: 0.1.0
 */
import type { ArtifactFilterTaskRunIdAny } from "./artifactFilterTaskRunIdAny";

/**
 * Filter by `Artifact.task_run_id`.
 */
export interface ArtifactFilterTaskRunId {
	/** A list of task run IDs to include */
	any_?: ArtifactFilterTaskRunIdAny;
}
