/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Prefect Prefect REST API
 * OpenAPI spec version: 0.1.0
 */
import type { ArtifactMetadataAnyOf } from "./artifactMetadataAnyOf";

/**
 * User-defined artifact metadata. Content must be string key and value pairs.
 */
export type ArtifactMetadata = ArtifactMetadataAnyOf | null;
