/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Prefect Prefect REST API
 * OpenAPI spec version: 0.1.0
 */
import type { ArtifactCollectionCreated } from "./artifactCollectionCreated";
import type { ArtifactCollectionData } from "./artifactCollectionData";
import type { ArtifactCollectionDescription } from "./artifactCollectionDescription";
import type { ArtifactCollectionFlowRunId } from "./artifactCollectionFlowRunId";
import type { ArtifactCollectionMetadata } from "./artifactCollectionMetadata";
import type { ArtifactCollectionTaskRunId } from "./artifactCollectionTaskRunId";
import type { ArtifactCollectionType } from "./artifactCollectionType";
import type { ArtifactCollectionUpdated } from "./artifactCollectionUpdated";

export interface ArtifactCollection {
	id: string;
	created: ArtifactCollectionCreated;
	updated: ArtifactCollectionUpdated;
	/** An optional unique reference key for this artifact. */
	key: string;
	/** The latest artifact ID associated with the key. */
	latest_id: string;
	/** An identifier that describes the shape of the data field. e.g. 'result', 'table', 'markdown' */
	type?: ArtifactCollectionType;
	/** A markdown-enabled description of the artifact. */
	description?: ArtifactCollectionDescription;
	/** Data associated with the artifact, e.g. a result.; structure depends on the artifact type. */
	data?: ArtifactCollectionData;
	/** User-defined artifact metadata. Content must be string key and value pairs. */
	metadata_?: ArtifactCollectionMetadata;
	/** The flow run associated with the artifact. */
	flow_run_id?: ArtifactCollectionFlowRunId;
	/** The task run associated with the artifact. */
	task_run_id?: ArtifactCollectionTaskRunId;
}
