/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Prefect Prefect REST API
 * OpenAPI spec version: 0.1.0
 */
import type { ArtifactFilterKeyAny } from "./artifactFilterKeyAny";
import type { ArtifactFilterKeyExists } from "./artifactFilterKeyExists";
import type { ArtifactFilterKeyLike } from "./artifactFilterKeyLike";

/**
 * Filter by `Artifact.key`.
 */
export interface ArtifactFilterKey {
	/** A list of artifact keys to include */
	any_?: ArtifactFilterKeyAny;
	/** A string to match artifact keys against. This can include SQL wildcard characters like `%` and `_`. */
	like_?: ArtifactFilterKeyLike;
	/** If `true`, only include artifacts with a non-null key. If `false`, only include artifacts with a null key. */
	exists_?: ArtifactFilterKeyExists;
}
