/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Prefect Prefect REST API
 * OpenAPI spec version: 0.1.0
 */

/**
 * A string to match artifact keys against. This can include SQL wildcard characters like `%` and `_`.
 */
export type ArtifactFilterKeyLike = string | null;
