/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Prefect Prefect REST API
 * OpenAPI spec version: 0.1.0
 */
import type { ArtifactFilterKey } from "./artifactFilterKey";

/**
 * Filter criteria for `Artifact.key`
 */
export type ArtifactFilterKeyProperty = ArtifactFilterKey | null;
