/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Prefect Prefect REST API
 * OpenAPI spec version: 0.1.0
 */
import type { ArtifactFilterType } from "./artifactFilterType";

/**
 * Filter criteria for `Artifact.type`
 */
export type ArtifactFilterTypeProperty = ArtifactFilterType | null;
