/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Prefect Prefect REST API
 * OpenAPI spec version: 0.1.0
 */
import type { ArtifactCollectionFilterLatestId } from "./artifactCollectionFilterLatestId";

/**
 * Filter criteria for `Artifact.id`
 */
export type ArtifactCollectionFilterLatestIdProperty =
	ArtifactCollectionFilterLatestId | null;
