import type { AutomationFilterCreatedProperty } from "./automationFilterCreatedProperty";
import type { AutomationFilterNameProperty } from "./automationFilterNameProperty";
/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Prefect Prefect REST API
 * OpenAPI spec version: 0.1.0
 */
import type { Operator } from "./operator";

export interface AutomationFilter {
	/** Operator for combining filter criteria. Defaults to 'and_'. */
	operator?: Operator;
	/** Filter criteria for `Automation.name` */
	name?: AutomationFilterNameProperty;
	/** Filter criteria for `Automation.created` */
	created?: AutomationFilterCreatedProperty;
}
