import type { AutomationActionsItem } from "./automationActionsItem";
import type { AutomationActionsOnResolveItem } from "./automationActionsOnResolveItem";
import type { AutomationActionsOnTriggerItem } from "./automationActionsOnTriggerItem";
import type { AutomationCreated } from "./automationCreated";
/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Prefect Prefect REST API
 * OpenAPI spec version: 0.1.0
 */
import type { AutomationTrigger } from "./automationTrigger";
import type { AutomationUpdated } from "./automationUpdated";

export interface Automation {
	/** The name of this automation */
	name: string;
	/** A longer description of this automation */
	description?: string;
	/** Whether this automation will be evaluated */
	enabled?: boolean;
	/** The criteria for which events this Automation covers and how it will respond to the presence or absence of those events */
	trigger: AutomationTrigger;
	/** The actions to perform when this Automation triggers */
	actions: AutomationActionsItem[];
	/** The actions to perform when an Automation goes into a triggered state */
	actions_on_trigger?: AutomationActionsOnTriggerItem[];
	/** The actions to perform when an Automation goes into a resolving state */
	actions_on_resolve?: AutomationActionsOnResolveItem[];
	id: string;
	created: AutomationCreated;
	updated: AutomationUpdated;
}
