import type { CompoundTriggerOutput } from "./compoundTriggerOutput";
/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Prefect Prefect REST API
 * OpenAPI spec version: 0.1.0
 */
import type { EventTrigger } from "./eventTrigger";
import type { SequenceTriggerOutput } from "./sequenceTriggerOutput";

/**
 * The criteria for which events this Automation covers and how it will respond to the presence or absence of those events
 */
export type AutomationTrigger =
	| EventTrigger
	| CompoundTriggerOutput
	| SequenceTriggerOutput;
