/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Prefect Prefect REST API
 * OpenAPI spec version: 0.1.0
 */
import type { BlockDocumentFilterNameAny } from "./blockDocumentFilterNameAny";
import type { BlockDocumentFilterNameLike } from "./blockDocumentFilterNameLike";

/**
 * Filter by `BlockDocument.name`.
 */
export interface BlockDocumentFilterName {
	/** A list of block names to include */
	any_?: BlockDocumentFilterNameAny;
	/** A string to match block names against. This can include SQL wildcard characters like `%` and `_`. */
	like_?: BlockDocumentFilterNameLike;
}
