/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Prefect Prefect REST API
 * OpenAPI spec version: 0.1.0
 */
import type { BlockTypeFilterNameLike } from "./blockTypeFilterNameLike";

/**
 * Filter by `BlockType.name`
 */
export interface BlockTypeFilterName {
	/** A case-insensitive partial match. For example,  passing 'marvin' will match 'marvin', 'sad-Marvin', and 'marvin-robot'. */
	like_?: BlockTypeFilterNameLike;
}
