import type { BlockTypeCreateCodeExample } from "./blockTypeCreateCodeExample";
import type { BlockTypeCreateDescription } from "./blockTypeCreateDescription";
import type { BlockTypeCreateDocumentationUrl } from "./blockTypeCreateDocumentationUrl";
/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Prefect Prefect REST API
 * OpenAPI spec version: 0.1.0
 */
import type { BlockTypeCreateLogoUrl } from "./blockTypeCreateLogoUrl";

/**
 * Data used by the Prefect REST API to create a block type.
 */
export interface BlockTypeCreate {
	/**
	 * A block type's name
	 * @pattern ^[^/%&><]+$
	 */
	name: string;
	/** A block type's slug */
	slug: string;
	/** Web URL for the block type's logo */
	logo_url?: BlockTypeCreateLogoUrl;
	/** Web URL for the block type's documentation */
	documentation_url?: BlockTypeCreateDocumentationUrl;
	/** A short blurb about the corresponding block's intended use */
	description?: BlockTypeCreateDescription;
	/** A code snippet demonstrating use of the corresponding block */
	code_example?: BlockTypeCreateCodeExample;
}
