import type { BlockDocumentFilterBlockTypeIdProperty } from "./blockDocumentFilterBlockTypeIdProperty";
import type { BlockDocumentFilterIdProperty } from "./blockDocumentFilterIdProperty";
import type { BlockDocumentFilterIsAnonymousProperty } from "./blockDocumentFilterIsAnonymousProperty";
import type { BlockDocumentFilterNameProperty } from "./blockDocumentFilterNameProperty";
/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Prefect Prefect REST API
 * OpenAPI spec version: 0.1.0
 */
import type { Operator } from "./operator";

/**
 * Filter BlockDocuments. Only BlockDocuments matching all criteria will be returned
 */
export interface BlockDocumentFilter {
	/** Operator for combining filter criteria. Defaults to 'and_'. */
	operator?: Operator;
	/** Filter criteria for `BlockDocument.id` */
	id?: BlockDocumentFilterIdProperty;
	/** Filter criteria for `BlockDocument.is_anonymous`. Defaults to excluding anonymous blocks. */
	is_anonymous?: BlockDocumentFilterIsAnonymousProperty;
	/** Filter criteria for `BlockDocument.block_type_id` */
	block_type_id?: BlockDocumentFilterBlockTypeIdProperty;
	/** Filter criteria for `BlockDocument.name` */
	name?: BlockDocumentFilterNameProperty;
}
