import type { BlockTypeCodeExample } from "./blockTypeCodeExample";
/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Prefect Prefect REST API
 * OpenAPI spec version: 0.1.0
 */
import type { BlockTypeCreated } from "./blockTypeCreated";
import type { BlockTypeDescription } from "./blockTypeDescription";
import type { BlockTypeDocumentationUrl } from "./blockTypeDocumentationUrl";
import type { BlockTypeLogoUrl } from "./blockTypeLogoUrl";
import type { BlockTypeUpdated } from "./blockTypeUpdated";

/**
 * An ORM representation of a block type
 */
export interface BlockType {
	id: string;
	created: BlockTypeCreated;
	updated: BlockTypeUpdated;
	/**
	 * A block type's name
	 * @pattern ^[^/%&><]+$
	 */
	name: string;
	/** A block type's slug */
	slug: string;
	/** Web URL for the block type's logo */
	logo_url?: BlockTypeLogoUrl;
	/** Web URL for the block type's documentation */
	documentation_url?: BlockTypeDocumentationUrl;
	/** A short blurb about the corresponding block's intended use */
	description?: BlockTypeDescription;
	/** A code snippet demonstrating use of the corresponding block */
	code_example?: BlockTypeCodeExample;
	/** Protected block types cannot be modified via API. */
	is_protected?: boolean;
}
