/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Prefect Prefect REST API
 * OpenAPI spec version: 0.1.0
 */
import type { BlockTypeFilterNameProperty } from "./blockTypeFilterNameProperty";
import type { BlockTypeFilterSlugProperty } from "./blockTypeFilterSlugProperty";

/**
 * Filter BlockTypes
 */
export interface BlockTypeFilter {
	/** Filter criteria for `BlockType.name` */
	name?: BlockTypeFilterNameProperty;
	/** Filter criteria for `BlockType.slug` */
	slug?: BlockTypeFilterSlugProperty;
}
