/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Prefect Prefect REST API
 * OpenAPI spec version: 0.1.0
 */
import type { BlockDocumentFilterIsAnonymousEq } from "./blockDocumentFilterIsAnonymousEq";

/**
 * Filter by `BlockDocument.is_anonymous`.
 */
export interface BlockDocumentFilterIsAnonymous {
	/** Filter block documents for only those that are or are not anonymous. */
	eq_?: BlockDocumentFilterIsAnonymousEq;
}
