/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Prefect Prefect REST API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Defines block document sorting options.
 */
export type BlockDocumentSort =
	(typeof BlockDocumentSort)[keyof typeof BlockDocumentSort];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const BlockDocumentSort = {
	NAME_DESC: "NAME_DESC",
	NAME_ASC: "NAME_ASC",
	BLOCK_TYPE_AND_NAME_ASC: "BLOCK_TYPE_AND_NAME_ASC",
} as const;
