/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Prefect Prefect REST API
 * OpenAPI spec version: 0.1.0
 */

/**
 * A list of block type ids to include
 */
export type BlockDocumentFilterBlockTypeIdAny = string[] | null;
