/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Prefect Prefect REST API
 * OpenAPI spec version: 0.1.0
 */
import type { BlockSchemaFilterVersionAny } from "./blockSchemaFilterVersionAny";

/**
 * Filter by `BlockSchema.capabilities`
 */
export interface BlockSchemaFilterVersion {
	/** A list of block schema versions. */
	any_?: BlockSchemaFilterVersionAny;
}
