/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Prefect Prefect REST API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Filter block documents for only those that are or are not anonymous.
 */
export type BlockDocumentFilterIsAnonymousEq = boolean | null;
