/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Prefect Prefect REST API
 * OpenAPI spec version: 0.1.0
 */
import type { BlockSchemaFilterIdAny } from "./blockSchemaFilterIdAny";

/**
 * Filter by BlockSchema.id
 */
export interface BlockSchemaFilterId {
	/** A list of IDs to include */
	any_?: BlockSchemaFilterIdAny;
}
