import type { BlockDocumentCreateData } from "./blockDocumentCreateData";
/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Prefect Prefect REST API
 * OpenAPI spec version: 0.1.0
 */
import type { BlockDocumentCreateName } from "./blockDocumentCreateName";

/**
 * Data used by the Prefect REST API to create a block document.
 */
export interface BlockDocumentCreate {
	/** The block document's name. Not required for anonymous block documents. */
	name?: BlockDocumentCreateName;
	/** The block document's data */
	data?: BlockDocumentCreateData;
	/** A block schema ID */
	block_schema_id: string;
	/** A block type ID */
	block_type_id: string;
	/** Whether the block is anonymous (anonymous blocks are usually created by Prefect automatically) */
	is_anonymous?: boolean;
}
