/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Prefect Prefect REST API
 * OpenAPI spec version: 0.1.0
 */
import type { BlockDocumentFilterBlockTypeIdAny } from "./blockDocumentFilterBlockTypeIdAny";

/**
 * Filter by `BlockDocument.block_type_id`.
 */
export interface BlockDocumentFilterBlockTypeId {
	/** A list of block type ids to include */
	any_?: BlockDocumentFilterBlockTypeIdAny;
}
