import type { BlockTypeUpdateCodeExample } from "./blockTypeUpdateCodeExample";
import type { BlockTypeUpdateDescription } from "./blockTypeUpdateDescription";
import type { BlockTypeUpdateDocumentationUrl } from "./blockTypeUpdateDocumentationUrl";
/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Prefect Prefect REST API
 * OpenAPI spec version: 0.1.0
 */
import type { BlockTypeUpdateLogoUrl } from "./blockTypeUpdateLogoUrl";

/**
 * Data used by the Prefect REST API to update a block type.
 */
export interface BlockTypeUpdate {
	logo_url?: BlockTypeUpdateLogoUrl;
	documentation_url?: BlockTypeUpdateDocumentationUrl;
	description?: BlockTypeUpdateDescription;
	code_example?: BlockTypeUpdateCodeExample;
}
