/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Prefect Prefect REST API
 * OpenAPI spec version: 0.1.0
 */
import type { BodyCountBlockDocumentsBlockDocumentsCountPostBlockDocuments } from "./bodyCountBlockDocumentsBlockDocumentsCountPostBlockDocuments";
import type { BodyCountBlockDocumentsBlockDocumentsCountPostBlockSchemas } from "./bodyCountBlockDocumentsBlockDocumentsCountPostBlockSchemas";
import type { BodyCountBlockDocumentsBlockDocumentsCountPostBlockTypes } from "./bodyCountBlockDocumentsBlockDocumentsCountPostBlockTypes";

export interface BodyCountBlockDocumentsBlockDocumentsCountPost {
	block_documents?: BodyCountBlockDocumentsBlockDocumentsCountPostBlockDocuments;
	block_types?: BodyCountBlockDocumentsBlockDocumentsCountPostBlockTypes;
	block_schemas?: BodyCountBlockDocumentsBlockDocumentsCountPostBlockSchemas;
}
