/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Prefect Prefect REST API
 * OpenAPI spec version: 0.1.0
 */
import type { BodyReadWorkPoolsWorkPoolsFilterPostWorkPools } from "./bodyReadWorkPoolsWorkPoolsFilterPostWorkPools";

export interface BodyReadWorkPoolsWorkPoolsFilterPost {
	work_pools?: BodyReadWorkPoolsWorkPoolsFilterPostWorkPools;
	/** @minimum 0 */
	offset?: number;
	/** Defaults to PREFECT_API_DEFAULT_LIMIT if not provided. */
	limit?: number;
}
