import type { DeploymentFilter } from "./deploymentFilter";
import type { FlowFilter } from "./flowFilter";
import type { FlowRunFilter } from "./flowRunFilter";
/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Prefect Prefect REST API
 * OpenAPI spec version: 0.1.0
 */
import type { FlowRunSort } from "./flowRunSort";
import type { TaskRunFilter } from "./taskRunFilter";
import type { WorkPoolFilter } from "./workPoolFilter";

export interface BodyReadFlowRunHistoryUiFlowRunsHistoryPost {
	sort?: FlowRunSort;
	/** @maximum 1000 */
	limit?: number;
	/** @minimum 0 */
	offset?: number;
	flows?: FlowFilter;
	flow_runs?: FlowRunFilter;
	task_runs?: TaskRunFilter;
	deployments?: DeploymentFilter;
	work_pools?: WorkPoolFilter;
}
