/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Prefect Prefect REST API
 * OpenAPI spec version: 0.1.0
 */
import type { BodyReadWorkQueueRunsWorkQueuesIdGetRunsPostAgentId } from "./bodyReadWorkQueueRunsWorkQueuesIdGetRunsPostAgentId";

export interface BodyReadWorkQueueRunsWorkQueuesIdGetRunsPost {
	/** Only flow runs scheduled to start before this time will be returned. */
	scheduled_before?: string;
	/** An optional unique identifier for the agent making this query. If provided, the Prefect REST API will track the last time this agent polled the work queue. */
	agent_id?: BodyReadWorkQueueRunsWorkQueuesIdGetRunsPostAgentId;
	/** Defaults to PREFECT_API_DEFAULT_LIMIT if not provided. */
	limit?: number;
}
