/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Prefect Prefect REST API
 * OpenAPI spec version: 0.1.0
 */

/**
 * The sender of the input
 */
export type BodyCreateFlowRunInputFlowRunsIdInputPostSender = string | null;
