/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Prefect Prefect REST API
 * OpenAPI spec version: 0.1.0
 */

export interface BodyScheduleDeploymentDeploymentsIdSchedulePost {
	/** The earliest date to schedule */
	start_time?: string;
	/** The latest date to schedule */
	end_time?: string;
	/** Runs will be scheduled until at least this long after the `start_time` */
	min_time?: number;
	/** The minimum number of runs to schedule */
	min_runs?: number;
	/** The maximum number of runs to schedule */
	max_runs?: number;
}
