/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Prefect Prefect REST API
 * OpenAPI spec version: 0.1.0
 */
import type { BodyValidateObjUiSchemasValidatePostJsonSchema } from "./bodyValidateObjUiSchemasValidatePostJsonSchema";
import type { BodyValidateObjUiSchemasValidatePostValues } from "./bodyValidateObjUiSchemasValidatePostValues";

export interface BodyValidateObjUiSchemasValidatePost {
	json_schema: BodyValidateObjUiSchemasValidatePostJsonSchema;
	values: BodyValidateObjUiSchemasValidatePostValues;
}
