/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Prefect Prefect REST API
 * OpenAPI spec version: 0.1.0
 */
import type { BodyCreateFlowRunInputFlowRunsIdInputPostSender } from "./bodyCreateFlowRunInputFlowRunsIdInputPostSender";

export interface BodyCreateFlowRunInputFlowRunsIdInputPost {
	/** The input key */
	key: string;
	/** The value of the input */
	value: Blob;
	/** The sender of the input */
	sender?: BodyCreateFlowRunInputFlowRunsIdInputPostSender;
}
