/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Prefect Prefect REST API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Manual override for active concurrency limit slots.
 */
export type BodyResetConcurrencyLimitByTagConcurrencyLimitsTagTagResetPostSlotOverride =
	| string[]
	| null;
