import type { DeploymentFilter } from "./deploymentFilter";
import type { DeploymentSort } from "./deploymentSort";
/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Prefect Prefect REST API
 * OpenAPI spec version: 0.1.0
 */
import type { FlowFilter } from "./flowFilter";
import type { FlowRunFilter } from "./flowRunFilter";
import type { TaskRunFilter } from "./taskRunFilter";
import type { WorkPoolFilter } from "./workPoolFilter";
import type { WorkQueueFilter } from "./workQueueFilter";

export interface BodyPaginateDeploymentsDeploymentsPaginatePost {
	/** @minimum 1 */
	page?: number;
	flows?: FlowFilter;
	flow_runs?: FlowRunFilter;
	task_runs?: TaskRunFilter;
	deployments?: DeploymentFilter;
	work_pools?: WorkPoolFilter;
	work_pool_queues?: WorkQueueFilter;
	sort?: DeploymentSort;
	/** Defaults to PREFECT_API_DEFAULT_LIMIT if not provided. */
	limit?: number;
}
