/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Prefect Prefect REST API
 * OpenAPI spec version: 0.1.0
 */

/**
 * An optional unique identifier for the agent making this query. If provided, the Prefect REST API will track the last time this agent polled the work queue.
 */
export type BodyReadWorkQueueRunsWorkQueuesIdGetRunsPostAgentId = string | null;
