import type { CompoundTriggerOutput } from "./compoundTriggerOutput";
/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Prefect Prefect REST API
 * OpenAPI spec version: 0.1.0
 */
import type { EventTrigger } from "./eventTrigger";
import type { SequenceTriggerOutput } from "./sequenceTriggerOutput";

export type CompoundTriggerOutputTriggersItem =
	| EventTrigger
	| CompoundTriggerOutput
	| SequenceTriggerOutput;
