/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Prefect Prefect REST API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Data used by the Prefect REST API to create a v2 concurrency limit.
 */
export interface ConcurrencyLimitV2Create {
	/** Whether the concurrency limit is active. */
	active?: boolean;
	/**
	 * The name of the concurrency limit.
	 * @pattern ^[^/%&><]+$
	 */
	name: string;
	/**
	 * The concurrency limit.
	 * @minimum 0
	 */
	limit: number;
	/**
	 * The number of active slots.
	 * @minimum 0
	 */
	active_slots?: number;
	/**
	 * The number of denied slots.
	 * @minimum 0
	 */
	denied_slots?: number;
	/**
	 * The decay rate for active slots when used as a rate limit.
	 * @minimum 0
	 */
	slot_decay_per_second?: number;
}
