/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Prefect Prefect REST API
 * OpenAPI spec version: 0.1.0
 */
import type { ConcurrencyLimitStrategy } from "./concurrencyLimitStrategy";

/**
 * Class for storing the concurrency config in database.
 */
export interface ConcurrencyOptions {
	collision_strategy: ConcurrencyLimitStrategy;
}
