/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Prefect Prefect REST API
 * OpenAPI spec version: 0.1.0
 */

export interface CountByState {
	COMPLETED?: number;
	PENDING?: number;
	RUNNING?: number;
	FAILED?: number;
	CANCELLED?: number;
	CRASHED?: number;
	PAUSED?: number;
	CANCELLING?: number;
	SCHEDULED?: number;
}
