import type { DependencyResultEndTime } from "./dependencyResultEndTime";
import type { DependencyResultEstimatedRunTime } from "./dependencyResultEstimatedRunTime";
import type { DependencyResultExpectedStartTime } from "./dependencyResultExpectedStartTime";
import type { DependencyResultStartTime } from "./dependencyResultStartTime";
import type { DependencyResultState } from "./dependencyResultState";
import type { DependencyResultTotalRunTime } from "./dependencyResultTotalRunTime";
/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Prefect Prefect REST API
 * OpenAPI spec version: 0.1.0
 */
import type { TaskRunResult } from "./taskRunResult";

export interface DependencyResult {
	id: string;
	name: string;
	upstream_dependencies: TaskRunResult[];
	state: DependencyResultState;
	expected_start_time: DependencyResultExpectedStartTime;
	start_time: DependencyResultStartTime;
	end_time: DependencyResultEndTime;
	total_run_time: DependencyResultTotalRunTime;
	estimated_run_time: DependencyResultEstimatedRunTime;
	untrackable_result: boolean;
}
