/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Prefect Prefect REST API
 * OpenAPI spec version: 0.1.0
 */
import type { DeploymentFlowRunCreateLabelsAnyOf } from "./deploymentFlowRunCreateLabelsAnyOf";

/**
 * A dictionary of key-value labels. Values can be strings, numbers, or booleans.
 */
export type DeploymentFlowRunCreateLabels =
	DeploymentFlowRunCreateLabelsAnyOf | null;
