/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Prefect Prefect REST API
 * OpenAPI spec version: 0.1.0
 */
import type { DeploymentFilterIdAny } from "./deploymentFilterIdAny";

/**
 * Filter by `Deployment.id`.
 */
export interface DeploymentFilterId {
	/** A list of deployment ids to include */
	any_?: DeploymentFilterIdAny;
}
