/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Prefect Prefect REST API
 * OpenAPI spec version: 0.1.0
 */
import type { DeploymentFilterWorkQueueName } from "./deploymentFilterWorkQueueName";

/**
 * Filter criteria for `Deployment.work_queue_name`
 */
export type DeploymentFilterWorkQueueNameProperty =
	DeploymentFilterWorkQueueName | null;
