/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Prefect Prefect REST API
 * OpenAPI spec version: 0.1.0
 */

/**
 * The last time the deployment was polled for status updates.
 */
export type DeploymentResponseLastPolled = string | null;
