/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Prefect Prefect REST API
 * OpenAPI spec version: 0.1.0
 */
import type { GlobalConcurrencyLimitResponse } from "./globalConcurrencyLimitResponse";

/**
 * The global concurrency limit object for enforcing the maximum number of flow runs that can be active at once.
 */
export type DeploymentResponseGlobalConcurrencyLimit =
	GlobalConcurrencyLimitResponse | null;
