/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Prefect Prefect REST API
 * OpenAPI spec version: 0.1.0
 */

/**
 * The path to the entrypoint for the workflow, relative to the `path`.
 */
export type DeploymentResponseEntrypoint = string | null;
