/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Prefect Prefect REST API
 * OpenAPI spec version: 0.1.0
 */

/**
 * The work queue for the deployment. If no work queue is set, work will not be scheduled.
 */
export type DeploymentResponseWorkQueueName = string | null;
