/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Prefect Prefect REST API
 * OpenAPI spec version: 0.1.0
 */
import type { DeploymentCreateParameterOpenapiSchemaAnyOf } from "./deploymentCreateParameterOpenapiSchemaAnyOf";

/**
 * The parameter schema of the flow, including defaults.
 */
export type DeploymentCreateParameterOpenapiSchema =
	DeploymentCreateParameterOpenapiSchemaAnyOf | null;
