/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Prefect Prefect REST API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Parameters for flow runs scheduled by the deployment.
 */
export type DeploymentCreateParameters = { [key: string]: unknown };
