/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Prefect Prefect REST API
 * OpenAPI spec version: 0.1.0
 */
import type { DeploymentFilterConcurrencyLimit } from "./deploymentFilterConcurrencyLimit";

/**
 * DEPRECATED: Prefer `Deployment.concurrency_limit_id` over `Deployment.concurrency_limit`. If provided, will be ignored for backwards-compatibility. Will be removed after December 2024.
 * @deprecated
 */
export type DeploymentFilterConcurrencyLimitProperty =
	DeploymentFilterConcurrencyLimit | null;
