import type { CronSchedule } from "./cronSchedule";
/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Prefect Prefect REST API
 * OpenAPI spec version: 0.1.0
 */
import type { IntervalSchedule } from "./intervalSchedule";
import type { RRuleSchedule } from "./rRuleSchedule";

/**
 * The schedule for the deployment.
 */
export type DeploymentScheduleSchedule =
	| IntervalSchedule
	| CronSchedule
	| RRuleSchedule;
