/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Prefect Prefect REST API
 * OpenAPI spec version: 0.1.0
 */

/**
 * The deployment id associated with this schedule.
 */
export type DeploymentScheduleDeploymentId = string | null;
