/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Prefect Prefect REST API
 * OpenAPI spec version: 0.1.0
 */

/**
 * The maximum number of scheduled runs for the schedule.
 */
export type DeploymentScheduleMaxScheduledRuns = number | null;
