/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Prefect Prefect REST API
 * OpenAPI spec version: 0.1.0
 */

/**
 * The path to the working directory for the workflow, relative to remote storage or an absolute path.
 */
export type DeploymentResponsePath = string | null;
