/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Prefect Prefect REST API
 * OpenAPI spec version: 0.1.0
 */
import type { DeploymentScheduleUpdateActive } from "./deploymentScheduleUpdateActive";
import type { DeploymentScheduleUpdateMaxScheduledRuns } from "./deploymentScheduleUpdateMaxScheduledRuns";
import type { DeploymentScheduleUpdateSchedule } from "./deploymentScheduleUpdateSchedule";

export interface DeploymentScheduleUpdate {
	/** Whether or not the schedule is active. */
	active?: DeploymentScheduleUpdateActive;
	/** The schedule for the deployment. */
	schedule?: DeploymentScheduleUpdateSchedule;
	/** The maximum number of scheduled runs for the schedule. */
	max_scheduled_runs?: DeploymentScheduleUpdateMaxScheduledRuns;
}
