/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Prefect Prefect REST API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Whether or not the schedule is active.
 */
export type DeploymentScheduleUpdateActive = boolean | null;
