/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Prefect Prefect REST API
 * OpenAPI spec version: 0.1.0
 */
import type { ConcurrencyOptions } from "./concurrencyOptions";

/**
 * The concurrency options for the deployment.
 */
export type DeploymentResponseConcurrencyOptions = ConcurrencyOptions | null;
