/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Prefect Prefect REST API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Defines deployment sorting options.
 */
export type DeploymentSort =
	(typeof DeploymentSort)[keyof typeof DeploymentSort];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DeploymentSort = {
	CREATED_DESC: "CREATED_DESC",
	UPDATED_DESC: "UPDATED_DESC",
	NAME_ASC: "NAME_ASC",
	NAME_DESC: "NAME_DESC",
} as const;
