import type { DeploymentFilterConcurrencyLimitProperty } from "./deploymentFilterConcurrencyLimitProperty";
import type { DeploymentFilterFlowOrDeploymentName } from "./deploymentFilterFlowOrDeploymentName";
import type { DeploymentFilterIdProperty } from "./deploymentFilterIdProperty";
import type { DeploymentFilterNameProperty } from "./deploymentFilterNameProperty";
import type { DeploymentFilterPausedProperty } from "./deploymentFilterPausedProperty";
import type { DeploymentFilterTagsProperty } from "./deploymentFilterTagsProperty";
import type { DeploymentFilterWorkQueueNameProperty } from "./deploymentFilterWorkQueueNameProperty";
/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Prefect Prefect REST API
 * OpenAPI spec version: 0.1.0
 */
import type { Operator } from "./operator";

/**
 * Filter for deployments. Only deployments matching all criteria will be returned.
 */
export interface DeploymentFilter {
	/** Operator for combining filter criteria. Defaults to 'and_'. */
	operator?: Operator;
	/** Filter criteria for `Deployment.id` */
	id?: DeploymentFilterIdProperty;
	/** Filter criteria for `Deployment.name` */
	name?: DeploymentFilterNameProperty;
	/** Filter criteria for `Deployment.name` or `Flow.name` */
	flow_or_deployment_name?: DeploymentFilterFlowOrDeploymentName;
	/** Filter criteria for `Deployment.paused` */
	paused?: DeploymentFilterPausedProperty;
	/** Filter criteria for `Deployment.tags` */
	tags?: DeploymentFilterTagsProperty;
	/** Filter criteria for `Deployment.work_queue_name` */
	work_queue_name?: DeploymentFilterWorkQueueNameProperty;
	/**
	 * DEPRECATED: Prefer `Deployment.concurrency_limit_id` over `Deployment.concurrency_limit`. If provided, will be ignored for backwards-compatibility. Will be removed after December 2024.
	 * @deprecated
	 */
	concurrency_limit?: DeploymentFilterConcurrencyLimitProperty;
}
