/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Prefect Prefect REST API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Only include events for resources with IDs starting with these prefixes
 */
export type EventAnyResourceFilterIdPrefix = string[] | null;
