/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Prefect Prefect REST API
 * OpenAPI spec version: 0.1.0
 */
import type { EventAnyResourceFilter } from "./eventAnyResourceFilter";

/**
 * Filter criteria for any resource involved in the event
 */
export type EventFilterAnyResource = EventAnyResourceFilter | null;
