/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Prefect Prefect REST API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Only include events for related resources in these roles
 */
export type EventRelatedFilterRole = string[] | null;
