/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Prefect Prefect REST API
 * OpenAPI spec version: 0.1.0
 */

/**
 * The count of events with the given filter value
 */
export interface EventCount {
	/** The value to use for filtering */
	value: string;
	/** The value to display for this count */
	label: string;
	/** The count of matching events */
	count: number;
	/** The start time of this group of events */
	start_time: string;
	/** The end time of this group of events */
	end_time: string;
}
