import type { EventPageNextPage } from "./eventPageNextPage";
/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Prefect Prefect REST API
 * OpenAPI spec version: 0.1.0
 */
import type { ReceivedEvent } from "./receivedEvent";

/**
 * A single page of events returned from the API, with an optional link to the
next page of results
 */
export interface EventPage {
	/** The Events matching the query */
	events: ReceivedEvent[];
	/** The total number of matching Events */
	total: number;
	/** The URL for the next page of results, if there are more */
	next_page: EventPageNextPage;
}
