/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Prefect Prefect REST API
 * OpenAPI spec version: 0.1.0
 */
import type { EventIDFilterId } from "./eventIDFilterId";

export interface EventIDFilter {
	/** Only include events with one of these IDs */
	id?: EventIDFilterId;
}
