/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Prefect Prefect REST API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Exclude events matching one of these names exactly
 */
export type EventNameFilterExcludeName = string[] | null;
