/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Prefect Prefect REST API
 * OpenAPI spec version: 0.1.0
 */
import type { EventRelatedFilter } from "./eventRelatedFilter";

/**
 * Filter criteria for the related resources of the event
 */
export type EventFilterRelated = EventRelatedFilter | null;
