/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Prefect Prefect REST API
 * OpenAPI spec version: 0.1.0
 */

export type EventOrder = (typeof EventOrder)[keyof typeof EventOrder];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EventOrder = {
	ASC: "ASC",
	DESC: "DESC",
} as const;
