/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Prefect Prefect REST API
 * OpenAPI spec version: 0.1.0
 */
import type { FlowRunJobVariablesAnyOf } from "./flowRunJobVariablesAnyOf";

/**
 * Variables used as overrides in the base job template
 */
export type FlowRunJobVariables = FlowRunJobVariablesAnyOf | null;
