/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Prefect Prefect REST API
 * OpenAPI spec version: 0.1.0
 */

/**
 * The type of retry this run is undergoing.
 */
export type FlowRunPolicyRetryType = "in_process" | "reschedule" | null;
