/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Prefect Prefect REST API
 * OpenAPI spec version: 0.1.0
 */

/**
 * A list of parent flow run ids to include
 */
export type FlowRunFilterParentFlowRunIdAny = string[] | null;
