/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Prefect Prefect REST API
 * OpenAPI spec version: 0.1.0
 */
import type { FlowRunFilterStateNameAny } from "./flowRunFilterStateNameAny";
import type { FlowRunFilterStateNameNotAny } from "./flowRunFilterStateNameNotAny";

/**
 * Filter by `FlowRun.state_name`.
 */
export interface FlowRunFilterStateName {
	/** A list of flow run state names to include */
	any_?: FlowRunFilterStateNameAny;
	/** A list of flow run state names to exclude */
	not_any_?: FlowRunFilterStateNameNotAny;
}
