import type { FlowRunFilterExpectedStartTimeAfter } from "./flowRunFilterExpectedStartTimeAfter";
/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Prefect Prefect REST API
 * OpenAPI spec version: 0.1.0
 */
import type { FlowRunFilterExpectedStartTimeBefore } from "./flowRunFilterExpectedStartTimeBefore";

/**
 * Filter by `FlowRun.expected_start_time`.
 */
export interface FlowRunFilterExpectedStartTime {
	/** Only include flow runs scheduled to start at or before this time */
	before_?: FlowRunFilterExpectedStartTimeBefore;
	/** Only include flow runs scheduled to start at or after this time */
	after_?: FlowRunFilterExpectedStartTimeAfter;
}
