/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Prefect Prefect REST API
 * OpenAPI spec version: 0.1.0
 */

/**
 * An optional idempotency key for the flow run. Used to ensure the same flow run is not created multiple times.
 */
export type FlowRunResponseIdempotencyKey = string | null;
