/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Prefect Prefect REST API
 * OpenAPI spec version: 0.1.0
 */
import type { FlowRunFilterFlowVersionAny } from "./flowRunFilterFlowVersionAny";

/**
 * Filter by `FlowRun.flow_version`.
 */
export interface FlowRunFilterFlowVersion {
	/** A list of flow run flow_versions to include */
	any_?: FlowRunFilterFlowVersionAny;
}
