/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Prefect Prefect REST API
 * OpenAPI spec version: 0.1.0
 */
import type { FlowFilterIdAny } from "./flowFilterIdAny";

/**
 * Filter by `Flow.id`.
 */
export interface FlowFilterId {
	/** A list of flow ids to include */
	any_?: FlowFilterIdAny;
}
