import type { FlowRunFilterNextScheduledStartTimeAfter } from "./flowRunFilterNextScheduledStartTimeAfter";
/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Prefect Prefect REST API
 * OpenAPI spec version: 0.1.0
 */
import type { FlowRunFilterNextScheduledStartTimeBefore } from "./flowRunFilterNextScheduledStartTimeBefore";

/**
 * Filter by `FlowRun.next_scheduled_start_time`.
 */
export interface FlowRunFilterNextScheduledStartTime {
	/** Only include flow runs with a next_scheduled_start_time or before this time */
	before_?: FlowRunFilterNextScheduledStartTimeBefore;
	/** Only include flow runs with a next_scheduled_start_time at or after this time */
	after_?: FlowRunFilterNextScheduledStartTimeAfter;
}
