/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Prefect Prefect REST API
 * OpenAPI spec version: 0.1.0
 */
import type { FlowRunFilterIdempotencyKeyAny } from "./flowRunFilterIdempotencyKeyAny";
import type { FlowRunFilterIdempotencyKeyNotAny } from "./flowRunFilterIdempotencyKeyNotAny";

/**
 * Filter by FlowRun.idempotency_key.
 */
export interface FlowRunFilterIdempotencyKey {
	/** A list of flow run idempotency keys to include */
	any_?: FlowRunFilterIdempotencyKeyAny;
	/** A list of flow run idempotency keys to exclude */
	not_any_?: FlowRunFilterIdempotencyKeyNotAny;
}
