import type { FlowFilterTagsAll } from "./flowFilterTagsAll";
import type { FlowFilterTagsIsNull } from "./flowFilterTagsIsNull";
/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Prefect Prefect REST API
 * OpenAPI spec version: 0.1.0
 */
import type { Operator } from "./operator";

/**
 * Filter by `Flow.tags`.
 */
export interface FlowFilterTags {
	/** Operator for combining filter criteria. Defaults to 'and_'. */
	operator?: Operator;
	/** A list of tags. Flows will be returned only if their tags are a superset of the list */
	all_?: FlowFilterTagsAll;
	/** If true, only include flows without tags */
	is_null_?: FlowFilterTagsIsNull;
}
