/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Prefect Prefect REST API
 * OpenAPI spec version: 0.1.0
 */
import type { FlowRunFilterExpectedStartTime } from "./flowRunFilterExpectedStartTime";

/**
 * Filter criteria for `FlowRun.expected_start_time`
 */
export type FlowRunFilterExpectedStartTimeProperty =
	FlowRunFilterExpectedStartTime | null;
