/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Prefect Prefect REST API
 * OpenAPI spec version: 0.1.0
 */
import type { Flow } from "./flow";

export interface FlowPaginationResponse {
	results: Flow[];
	count: number;
	limit: number;
	pages: number;
	page: number;
}
