/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Prefect Prefect REST API
 * OpenAPI spec version: 0.1.0
 */
import type { FlowRunNotificationPolicyFilterIsActive } from "./flowRunNotificationPolicyFilterIsActive";

/**
 * Filter criteria for `FlowRunNotificationPolicy.is_active`.
 */
export type FlowRunNotificationPolicyFilterIsActiveProperty =
	FlowRunNotificationPolicyFilterIsActive | null;
