/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Prefect Prefect REST API
 * OpenAPI spec version: 0.1.0
 */
import type { FlowRunFilterIdAny } from "./flowRunFilterIdAny";
import type { FlowRunFilterIdNotAny } from "./flowRunFilterIdNotAny";

/**
 * Filter by `FlowRun.id`.
 */
export interface FlowRunFilterId {
	/** A list of flow run ids to include */
	any_?: FlowRunFilterIdAny;
	/** A list of flow run ids to exclude */
	not_any_?: FlowRunFilterIdNotAny;
}
