/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Prefect Prefect REST API
 * OpenAPI spec version: 0.1.0
 */

/**
 * A list of flow run parent_task_run_ids to include
 */
export type FlowRunFilterParentTaskRunIdAny = string[] | null;
