/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Prefect Prefect REST API
 * OpenAPI spec version: 0.1.0
 */
import type { FlowCreated } from "./flowCreated";
import type { FlowLabels } from "./flowLabels";
import type { FlowUpdated } from "./flowUpdated";

/**
 * An ORM representation of flow data.
 */
export interface Flow {
	id: string;
	created: FlowCreated;
	updated: FlowUpdated;
	/**
	 * The name of the flow
	 * @pattern ^[^/%&><]+$
	 */
	name: string;
	/** A list of flow tags */
	tags?: string[];
	/** A dictionary of key-value labels. Values can be strings, numbers, or booleans. */
	labels?: FlowLabels;
}
