import type { FlowRunFilterParentTaskRunIdAny } from "./flowRunFilterParentTaskRunIdAny";
import type { FlowRunFilterParentTaskRunIdIsNull } from "./flowRunFilterParentTaskRunIdIsNull";
/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Prefect Prefect REST API
 * OpenAPI spec version: 0.1.0
 */
import type { Operator } from "./operator";

/**
 * Filter by `FlowRun.parent_task_run_id`.
 */
export interface FlowRunFilterParentTaskRunId {
	/** Operator for combining filter criteria. Defaults to 'and_'. */
	operator?: Operator;
	/** A list of flow run parent_task_run_ids to include */
	any_?: FlowRunFilterParentTaskRunIdAny;
	/** If true, only include flow runs without parent_task_run_id */
	is_null_?: FlowRunFilterParentTaskRunIdIsNull;
}
