/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Prefect Prefect REST API
 * OpenAPI spec version: 0.1.0
 */
import type { CreatedBy } from "./createdBy";

/**
 * Optional information about the creator of this flow run.
 */
export type FlowRunResponseCreatedBy = CreatedBy | null;
