/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Prefect Prefect REST API
 * OpenAPI spec version: 0.1.0
 */
import type { FlowRunFilterParentFlowRunId } from "./flowRunFilterParentFlowRunId";

/**
 * Filter criteria for subflows of the given flow runs
 */
export type FlowRunFilterParentFlowRunIdProperty =
	FlowRunFilterParentFlowRunId | null;
