/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Prefect Prefect REST API
 * OpenAPI spec version: 0.1.0
 */

/**
 * The id of the flow run as returned by an infrastructure block.
 */
export type FlowRunResponseInfrastructurePid = string | null;
