/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Prefect Prefect REST API
 * OpenAPI spec version: 0.1.0
 */
import type { StateCreate } from "./stateCreate";

/**
 * The state of the flow run to create
 */
export type FlowRunCreateState = StateCreate | null;
