/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Prefect Prefect REST API
 * OpenAPI spec version: 0.1.0
 */

/**
 * DEPRECATED: The id of the deployment associated with this flow run, if available.
 * @deprecated
 */
export type FlowRunCreateDeploymentId = string | null;
