/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Prefect Prefect REST API
 * OpenAPI spec version: 0.1.0
 */
import type { FlowRunFilterEndTime } from "./flowRunFilterEndTime";

/**
 * Filter criteria for `FlowRun.end_time`
 */
export type FlowRunFilterEndTimeProperty = FlowRunFilterEndTime | null;
