/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Prefect Prefect REST API
 * OpenAPI spec version: 0.1.0
 */
import type { FlowFilterDeployment } from "./flowFilterDeployment";

/**
 * Filter criteria for Flow deployments
 */
export type FlowFilterDeploymentProperty = FlowFilterDeployment | null;
