/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Prefect Prefect REST API
 * OpenAPI spec version: 0.1.0
 */
import type { HistoryResponseState } from "./historyResponseState";

/**
 * Represents a history of aggregation states over an interval
 */
export interface HistoryResponse {
	/** The start date of the interval. */
	interval_start: string;
	/** The end date of the interval. */
	interval_end: string;
	/** A list of state histories during the interval. */
	states: HistoryResponseState[];
}
