/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Prefect Prefect REST API
 * OpenAPI spec version: 0.1.0
 */
import type { LogCreateFlowRunId } from "./logCreateFlowRunId";
import type { LogCreateTaskRunId } from "./logCreateTaskRunId";

/**
 * Data used by the Prefect REST API to create a log.
 */
export interface LogCreate {
	/** The logger name. */
	name: string;
	/** The log level. */
	level: number;
	/** The log message. */
	message: string;
	/** The log timestamp. */
	timestamp: string;
	flow_run_id?: LogCreateFlowRunId;
	task_run_id?: LogCreateTaskRunId;
}
