import type { LogFilterFlowRunIdProperty } from "./logFilterFlowRunIdProperty";
import type { LogFilterLevelProperty } from "./logFilterLevelProperty";
import type { LogFilterTaskRunIdProperty } from "./logFilterTaskRunIdProperty";
import type { LogFilterTimestampProperty } from "./logFilterTimestampProperty";
/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Prefect Prefect REST API
 * OpenAPI spec version: 0.1.0
 */
import type { Operator } from "./operator";

/**
 * Filter logs. Only logs matching all criteria will be returned
 */
export interface LogFilter {
	/** Operator for combining filter criteria. Defaults to 'and_'. */
	operator?: Operator;
	/** Filter criteria for `Log.level` */
	level?: LogFilterLevelProperty;
	/** Filter criteria for `Log.timestamp` */
	timestamp?: LogFilterTimestampProperty;
	/** Filter criteria for `Log.flow_run_id` */
	flow_run_id?: LogFilterFlowRunIdProperty;
	/** Filter criteria for `Log.task_run_id` */
	task_run_id?: LogFilterTaskRunIdProperty;
}
