/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Prefect Prefect REST API
 * OpenAPI spec version: 0.1.0
 */
import type { LogFilterTaskRunId } from "./logFilterTaskRunId";

/**
 * Filter criteria for `Log.task_run_id`
 */
export type LogFilterTaskRunIdProperty = LogFilterTaskRunId | null;
