/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Prefect Prefect REST API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Include logs with a level greater than or equal to this level
 */
export type LogFilterLevelGe = number | null;
