/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Prefect Prefect REST API
 * OpenAPI spec version: 0.1.0
 */
import type { LogFilterTaskRunIdAny } from "./logFilterTaskRunIdAny";
import type { LogFilterTaskRunIdIsNull } from "./logFilterTaskRunIdIsNull";

/**
 * Filter by `Log.task_run_id`.
 */
export interface LogFilterTaskRunId {
	/** A list of task run IDs to include */
	any_?: LogFilterTaskRunIdAny;
	/** If true, only include logs without a task run id */
	is_null_?: LogFilterTaskRunIdIsNull;
}
