import type { LogFilterTimestampAfter } from "./logFilterTimestampAfter";
/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Prefect Prefect REST API
 * OpenAPI spec version: 0.1.0
 */
import type { LogFilterTimestampBefore } from "./logFilterTimestampBefore";

/**
 * Filter by `Log.timestamp`.
 */
export interface LogFilterTimestamp {
	/** Only include logs with a timestamp at or before this time */
	before_?: LogFilterTimestampBefore;
	/** Only include logs with a timestamp at or after this time */
	after_?: LogFilterTimestampAfter;
}
