/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Prefect Prefect REST API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Operators for combining filter criteria.
 */
export type Operator = (typeof Operator)[keyof typeof Operator];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const Operator = {
	and_: "and_",
	or_: "or_",
} as const;
