/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Prefect Prefect REST API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Represents a parameter input to a task run.
 */
export interface Parameter {
	input_type?: "parameter";
	name: string;
}
