import type { PauseAutomationAutomationId } from "./pauseAutomationAutomationId";
/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Prefect Prefect REST API
 * OpenAPI spec version: 0.1.0
 */
import type { PauseAutomationSource } from "./pauseAutomationSource";

/**
 * Pauses a Work Queue
 */
export interface PauseAutomation {
	type?: "pause-automation";
	/** Whether this Action applies to a specific selected automation (given by `automation_id`), or to an automation that is inferred from the triggering event.  If the source is 'inferred', the `automation_id` may not be set.  If the source is 'selected', the `automation_id` must be set. */
	source?: PauseAutomationSource;
	/** The identifier of the automation to act on */
	automation_id?: PauseAutomationAutomationId;
}
