/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Prefect Prefect REST API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Whether this Action applies to a specific selected automation (given by `automation_id`), or to an automation that is inferred from the triggering event.  If the source is 'inferred', the `automation_id` may not be set.  If the source is 'selected', the `automation_id` must be set.
 */
export type PauseAutomationSource =
	(typeof PauseAutomationSource)[keyof typeof PauseAutomationSource];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PauseAutomationSource = {
	selected: "selected",
	inferred: "inferred",
} as const;
