/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Prefect Prefect REST API
 * OpenAPI spec version: 0.1.0
 */
import type { PauseWorkPoolSource } from "./pauseWorkPoolSource";
import type { PauseWorkPoolWorkPoolId } from "./pauseWorkPoolWorkPoolId";

/**
 * Pauses a Work Pool
 */
export interface PauseWorkPool {
	type?: "pause-work-pool";
	/** Whether this Action applies to a specific selected work pool (given by `work_pool_id`), or to a work pool that is inferred from the triggering event.  If the source is 'inferred', the `work_pool_id` may not be set.  If the source is 'selected', the `work_pool_id` must be set. */
	source?: PauseWorkPoolSource;
	/** The identifier of the work pool to pause */
	work_pool_id?: PauseWorkPoolWorkPoolId;
}
