/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Prefect Prefect REST API
 * OpenAPI spec version: 0.1.0
 */

export type ReadFlowRunGraphV2FlowRunsIdGraphV2GetParams = {
	/**
	 * Only include runs that start or end after this time.
	 */
	since?: string;
};
