/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Prefect Prefect REST API
 * OpenAPI spec version: 0.1.0
 */

export type ReadBlockDocumentByNameForBlockTypeBlockTypesSlugSlugBlockDocumentsNameBlockDocumentNameGetParams =
	{
		/**
		 * Whether to include sensitive values in the block document.
		 */
		include_secrets?: boolean;
	};
