/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Prefect Prefect REST API
 * OpenAPI spec version: 0.1.0
 */

/**
 * A Resource with a specific role in an Event
 */
export interface RelatedResource {
	[key: string]: string;
}
