/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Prefect Prefect REST API
 * OpenAPI spec version: 0.1.0
 */

/**
 * An observable business object of interest to the user
 */
export interface Resource {
	[key: string]: string;
}
