import type { ResumeDeploymentDeploymentId } from "./resumeDeploymentDeploymentId";
/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Prefect Prefect REST API
 * OpenAPI spec version: 0.1.0
 */
import type { ResumeDeploymentSource } from "./resumeDeploymentSource";

/**
 * Resumes the given Deployment
 */
export interface ResumeDeployment {
	type?: "resume-deployment";
	/** Whether this Action applies to a specific selected deployment (given by `deployment_id`), or to a deployment that is inferred from the triggering event.  If the source is 'inferred', the `deployment_id` may not be set.  If the source is 'selected', the `deployment_id` must be set. */
	source?: ResumeDeploymentSource;
	/** The identifier of the deployment */
	deployment_id?: ResumeDeploymentDeploymentId;
}
