/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Prefect Prefect REST API
 * OpenAPI spec version: 0.1.0
 */

/**
 * The identifier of the work pool to pause
 */
export type ResumeWorkPoolWorkPoolId = string | null;
