/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Prefect Prefect REST API
 * OpenAPI spec version: 0.1.0
 */
import type { RunDeploymentParametersAnyOf } from "./runDeploymentParametersAnyOf";

/**
 * The parameters to pass to the deployment, or None to use the deployment's default parameters
 */
export type RunDeploymentParameters = RunDeploymentParametersAnyOf | null;
