/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Prefect Prefect REST API
 * OpenAPI spec version: 0.1.0
 */

/**
 * A filter for a saved search model. Intended for use by the Prefect UI.
 */
export interface SavedSearchFilter {
	/** The object over which to filter. */
	object: string;
	/** The property of the object on which to filter. */
	property: string;
	/** The type of the property. */
	type: string;
	/** The operator to apply to the object. For example, `equals`. */
	operation: string;
	/** A JSON-compatible value for the filter. */
	value: unknown;
}
