import type { StateData } from "./stateData";
import type { StateDetails } from "./stateDetails";
import type { StateMessage } from "./stateMessage";
import type { StateName } from "./stateName";
/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Prefect Prefect REST API
 * OpenAPI spec version: 0.1.0
 */
import type { StateType } from "./stateType";

/**
 * Represents the state of a run.
 */
export interface State {
	id: string;
	type: StateType;
	name?: StateName;
	timestamp?: string;
	message?: StateMessage;
	/** Data associated with the state, e.g. a result. Content must be storable as JSON. */
	data?: StateData;
	state_details?: StateDetails;
}
