import type { StateCreateData } from "./stateCreateData";
import type { StateCreateMessage } from "./stateCreateMessage";
import type { StateCreateName } from "./stateCreateName";
import type { StateDetails } from "./stateDetails";
/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Prefect Prefect REST API
 * OpenAPI spec version: 0.1.0
 */
import type { StateType } from "./stateType";

/**
 * Data used by the Prefect REST API to create a new state.
 */
export interface StateCreate {
	/** The type of the state to create */
	type: StateType;
	/** The name of the state to create */
	name?: StateCreateName;
	/** The message of the state to create */
	message?: StateCreateMessage;
	/** The data of the state to create */
	data?: StateCreateData;
	/** The details of the state to create */
	state_details?: StateDetails;
}
