/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Prefect Prefect REST API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Suspends a flow run associated with the trigger
 */
export interface SuspendFlowRun {
	type?: "suspend-flow-run";
}
