import type { TaskRunCreateCacheExpiration } from "./taskRunCreateCacheExpiration";
import type { TaskRunCreateCacheKey } from "./taskRunCreateCacheKey";
import type { TaskRunCreateFlowRunId } from "./taskRunCreateFlowRunId";
/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Prefect Prefect REST API
 * OpenAPI spec version: 0.1.0
 */
import type { TaskRunCreateId } from "./taskRunCreateId";
import type { TaskRunCreateLabels } from "./taskRunCreateLabels";
import type { TaskRunCreateState } from "./taskRunCreateState";
import type { TaskRunCreateTaskInputs } from "./taskRunCreateTaskInputs";
import type { TaskRunCreateTaskVersion } from "./taskRunCreateTaskVersion";
import type { TaskRunPolicy } from "./taskRunPolicy";

/**
 * Data used by the Prefect REST API to create a task run
 */
export interface TaskRunCreate {
	/** The ID to assign to the task run. If not provided, a random UUID will be generated. */
	id?: TaskRunCreateId;
	/** The state of the task run to create */
	state?: TaskRunCreateState;
	name?: string;
	/** The flow run id of the task run. */
	flow_run_id?: TaskRunCreateFlowRunId;
	/** A unique identifier for the task being run. */
	task_key: string;
	/** A dynamic key used to differentiate between multiple runs of the same task within the same flow run. */
	dynamic_key: string;
	/** An optional cache key. If a COMPLETED state associated with this cache key is found, the cached COMPLETED state will be used instead of executing the task run. */
	cache_key?: TaskRunCreateCacheKey;
	/** Specifies when the cached state should expire. */
	cache_expiration?: TaskRunCreateCacheExpiration;
	/** The version of the task being run. */
	task_version?: TaskRunCreateTaskVersion;
	empirical_policy?: TaskRunPolicy;
	/** A list of tags for the task run. */
	tags?: string[];
	/** A dictionary of key-value labels. Values can be strings, numbers, or booleans. */
	labels?: TaskRunCreateLabels;
	/** The inputs to the task run. */
	task_inputs?: TaskRunCreateTaskInputs;
}
