import type { TaskRunFilterStartTimeAfter } from "./taskRunFilterStartTimeAfter";
/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Prefect Prefect REST API
 * OpenAPI spec version: 0.1.0
 */
import type { TaskRunFilterStartTimeBefore } from "./taskRunFilterStartTimeBefore";
import type { TaskRunFilterStartTimeIsNull } from "./taskRunFilterStartTimeIsNull";

/**
 * Filter by `TaskRun.start_time`.
 */
export interface TaskRunFilterStartTime {
	/** Only include task runs starting at or before this time */
	before_?: TaskRunFilterStartTimeBefore;
	/** Only include task runs starting at or after this time */
	after_?: TaskRunFilterStartTimeAfter;
	/** If true, only return task runs without a start time */
	is_null_?: TaskRunFilterStartTimeIsNull;
}
