import type { Constant } from "./constant";
import type { Parameter } from "./parameter";
/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Prefect Prefect REST API
 * OpenAPI spec version: 0.1.0
 */
import type { TaskRunResult } from "./taskRunResult";

export type TaskRunTaskInputsItem = TaskRunResult | Parameter | Constant;
