/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Prefect Prefect REST API
 * OpenAPI spec version: 0.1.0
 */
import type { Operator } from "./operator";
import type { TaskRunFilterStateNameProperty } from "./taskRunFilterStateNameProperty";
import type { TaskRunFilterStateTypeProperty } from "./taskRunFilterStateTypeProperty";

/**
 * Filter by `TaskRun.type` and `TaskRun.name`.
 */
export interface TaskRunFilterState {
	/** Operator for combining filter criteria. Defaults to 'and_'. */
	operator?: Operator;
	/** Filter criteria for `TaskRun.state_type` */
	type?: TaskRunFilterStateTypeProperty;
	/** Filter criteria for `TaskRun.state_name` */
	name?: TaskRunFilterStateNameProperty;
}
