/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Prefect Prefect REST API
 * OpenAPI spec version: 0.1.0
 */

/**
 * A delay time or list of delay times between retries, in seconds.
 */
export type TaskRunPolicyRetryDelay = number | number[] | null;
