/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Prefect Prefect REST API
 * OpenAPI spec version: 0.1.0
 */

/**
 * If true, only return task runs without a start time
 */
export type TaskRunFilterStartTimeIsNull = boolean | null;
