/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Prefect Prefect REST API
 * OpenAPI spec version: 0.1.0
 */
import type { TaskRunPolicyRetries } from "./taskRunPolicyRetries";
import type { TaskRunPolicyRetryDelay } from "./taskRunPolicyRetryDelay";
import type { TaskRunPolicyRetryJitterFactor } from "./taskRunPolicyRetryJitterFactor";

/**
 * Defines of how a task run should retry.
 */
export interface TaskRunPolicy {
	/**
	 * The maximum number of retries. Field is not used. Please use `retries` instead.
	 * @deprecated
	 */
	max_retries?: number;
	/**
	 * The delay between retries. Field is not used. Please use `retry_delay` instead.
	 * @deprecated
	 */
	retry_delay_seconds?: number;
	/** The number of retries. */
	retries?: TaskRunPolicyRetries;
	/** A delay time or list of delay times between retries, in seconds. */
	retry_delay?: TaskRunPolicyRetryDelay;
	/** Determines the amount a retry should jitter */
	retry_jitter_factor?: TaskRunPolicyRetryJitterFactor;
}
