/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Prefect Prefect REST API
 * OpenAPI spec version: 0.1.0
 */

/**
 * The next time the task run is scheduled to start.
 */
export type TaskRunNextScheduledStartTime = string | null;
