/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Prefect Prefect REST API
 * OpenAPI spec version: 0.1.0
 */
import type { Operator } from "./operator";
import type { TaskRunFilterTagsAll } from "./taskRunFilterTagsAll";
import type { TaskRunFilterTagsIsNull } from "./taskRunFilterTagsIsNull";

/**
 * Filter by `TaskRun.tags`.
 */
export interface TaskRunFilterTags {
	/** Operator for combining filter criteria. Defaults to 'and_'. */
	operator?: Operator;
	/** A list of tags. Task runs will be returned only if their tags are a superset of the list */
	all_?: TaskRunFilterTagsAll;
	/** If true, only include task runs without tags */
	is_null_?: TaskRunFilterTagsIsNull;
}
