/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Prefect Prefect REST API
 * OpenAPI spec version: 0.1.0
 */
import type { TaskRunFilterStateTypeAny } from "./taskRunFilterStateTypeAny";

/**
 * Filter by `TaskRun.state_type`.
 */
export interface TaskRunFilterStateType {
	/** A list of task run state types to include */
	any_?: TaskRunFilterStateTypeAny;
}
