/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Prefect Prefect REST API
 * OpenAPI spec version: 0.1.0
 */

/**
 * The task run's expected start time.
 */
export type TaskRunExpectedStartTime = string | null;
