/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Prefect Prefect REST API
 * OpenAPI spec version: 0.1.0
 */
import type { TaskRunFilterStateName } from "./taskRunFilterStateName";

/**
 * Filter criteria for `TaskRun.state_name`
 */
export type TaskRunFilterStateNameProperty = TaskRunFilterStateName | null;
