/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Prefect Prefect REST API
 * OpenAPI spec version: 0.1.0
 */

export type TimeUnit = (typeof TimeUnit)[keyof typeof TimeUnit];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TimeUnit = {
	week: "week",
	day: "day",
	hour: "hour",
	minute: "minute",
	second: "second",
} as const;
