/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Prefect Prefect REST API
 * OpenAPI spec version: 0.1.0
 */

/**
 * The labels to update
 */
export type UpdateFlowRunLabelsFlowRunsIdLabelsPatchBody = {
	[key: string]: unknown;
};
