/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Prefect Prefect REST API
 * OpenAPI spec version: 0.1.0
 */
import type { VariableValueAnyOf } from "./variableValueAnyOf";

/**
 * The value of the variable
 */
export type VariableValue =
	| string
	| number
	| boolean
	| number
	| VariableValueAnyOf
	| unknown[]
	| null;
