/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Prefect Prefect REST API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Defines variables sorting options.
 */
export type VariableSort = (typeof VariableSort)[keyof typeof VariableSort];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const VariableSort = {
	CREATED_DESC: "CREATED_DESC",
	UPDATED_DESC: "UPDATED_DESC",
	NAME_DESC: "NAME_DESC",
	NAME_ASC: "NAME_ASC",
} as const;
