/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Prefect Prefect REST API
 * OpenAPI spec version: 0.1.0
 */
import type { VariableUpdateValueAnyOf } from "./variableUpdateValueAnyOf";

/**
 * The value of the variable
 */
export type VariableUpdateValue =
	| string
	| number
	| boolean
	| number
	| VariableUpdateValueAnyOf
	| unknown[]
	| null;
