/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Prefect Prefect REST API
 * OpenAPI spec version: 0.1.0
 */
import type { VariableCreateValue } from "./variableCreateValue";

/**
 * Data used by the Prefect REST API to create a Variable.
 */
export interface VariableCreate {
	/**
	 * The name of the variable
	 * @maxLength 255
	 */
	name: string;
	/** The value of the variable */
	value: VariableCreateValue;
	/** A list of variable tags */
	tags?: string[];
}
