/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Prefect Prefect REST API
 * OpenAPI spec version: 0.1.0
 */
import type { Operator } from "./operator";
import type { WorkerFilterLastHeartbeatTimeProperty } from "./workerFilterLastHeartbeatTimeProperty";
import type { WorkerFilterStatusProperty } from "./workerFilterStatusProperty";

/**
 * Filter by `Worker.last_heartbeat_time`.
 */
export interface WorkerFilter {
	/** Operator for combining filter criteria. Defaults to 'and_'. */
	operator?: Operator;
	/** Filter criteria for `Worker.last_heartbeat_time` */
	last_heartbeat_time?: WorkerFilterLastHeartbeatTimeProperty;
	/** Filter criteria for `Worker.status` */
	status?: WorkerFilterStatusProperty;
}
