/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Prefect Prefect REST API
 * OpenAPI spec version: 0.1.0
 */

/**
 * The queue's priority. Lower values are higher priority (1 is the highest).
 */
export type WorkQueueCreatePriority = number | null;
