/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Prefect Prefect REST API
 * OpenAPI spec version: 0.1.0
 */
import type { WorkQueueStatus } from "./workQueueStatus";

/**
 * The queue status.
 */
export type WorkQueueResponseStatus = WorkQueueStatus | null;
