/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Prefect Prefect REST API
 * OpenAPI spec version: 0.1.0
 */

/**
 * The last time an agent polled this queue for work.
 */
export type WorkQueueResponseLastPolled = string | null;
