import type { WorkPoolBaseJobTemplate } from "./workPoolBaseJobTemplate";
import type { WorkPoolConcurrencyLimit } from "./workPoolConcurrencyLimit";
/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Prefect Prefect REST API
 * OpenAPI spec version: 0.1.0
 */
import type { WorkPoolCreated } from "./workPoolCreated";
import type { WorkPoolDefaultQueueId } from "./workPoolDefaultQueueId";
import type { WorkPoolDescription } from "./workPoolDescription";
import type { WorkPoolStatusProperty } from "./workPoolStatusProperty";
import type { WorkPoolUpdated } from "./workPoolUpdated";

/**
 * An ORM representation of a work pool
 */
export interface WorkPool {
	id: string;
	created: WorkPoolCreated;
	updated: WorkPoolUpdated;
	/**
	 * The name of the work pool.
	 * @pattern ^[^/%&><]+$
	 */
	name: string;
	/** A description of the work pool. */
	description?: WorkPoolDescription;
	/** The work pool type. */
	type: string;
	/** The work pool's base job template. */
	base_job_template?: WorkPoolBaseJobTemplate;
	/** Pausing the work pool stops the delivery of all work. */
	is_paused?: boolean;
	/** A concurrency limit for the work pool. */
	concurrency_limit?: WorkPoolConcurrencyLimit;
	/** The current status of the work pool. */
	status?: WorkPoolStatusProperty;
	/** The id of the pool's default queue. */
	default_queue_id?: WorkPoolDefaultQueueId;
}
