/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Prefect Prefect REST API
 * OpenAPI spec version: 0.1.0
 */
import type { WorkQueueFilterId } from "./workQueueFilterId";

/**
 * Filter criteria for `WorkQueue.id`
 */
export type WorkQueueFilterIdProperty = WorkQueueFilterId | null;
