/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Prefect Prefect REST API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Enumeration of worker statuses.
 */
export type WorkerStatus = (typeof WorkerStatus)[keyof typeof WorkerStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const WorkerStatus = {
	ONLINE: "ONLINE",
	OFFLINE: "OFFLINE",
} as const;
