/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Prefect Prefect REST API
 * OpenAPI spec version: 0.1.0
 */
import type { WorkPoolFilterTypeAny } from "./workPoolFilterTypeAny";

/**
 * Filter by `WorkPool.type`.
 */
export interface WorkPoolFilterType {
	/** A list of work pool types to include */
	any_?: WorkPoolFilterTypeAny;
}
