/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Prefect Prefect REST API
 * OpenAPI spec version: 0.1.0
 */
import type { WorkerFilterStatus } from "./workerFilterStatus";

/**
 * Filter criteria for `Worker.status`
 */
export type WorkerFilterStatusProperty = WorkerFilterStatus | null;
