/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Prefect Prefect REST API
 * OpenAPI spec version: 0.1.0
 */

/**
 * A list of work pool names to include
 */
export type WorkPoolFilterNameAny = string[] | null;
