/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Prefect Prefect REST API
 * OpenAPI spec version: 0.1.0
 */

/**
 * The number of seconds to expect between heartbeats sent by the worker.
 */
export type WorkerResponseHeartbeatIntervalSeconds = number | null;
