import prefect.settings
from prefect.cli._types import LazyTyperGroup
from prefect.cli.root import app

_LAZY_COMMANDS: dict[str, tuple[str, ...] | str] = {
    "api": "prefect.cli.api",
    "artifact": "prefect.cli.artifact",
    "block": "prefect.cli.block",
    "blocks": "prefect.cli.block",
    "cloud": (
        "prefect.cli.cloud",
        "prefect.cli.cloud.ip_allowlist",
        "prefect.cli.cloud.webhook",
    ),
    "concurrency-limit": "prefect.cli.concurrency_limit",
    "concurrency-limits": "prefect.cli.concurrency_limit",
    "config": "prefect.cli.config",
    "dashboard": "prefect.cli.dashboard",
    "deploy": "prefect.cli.deploy",
    "init": "prefect.cli.deploy",
    "deployment": "prefect.cli.deployment",
    "deployments": "prefect.cli.deployment",
    "dev": "prefect.cli.dev",
    "event": "prefect.cli.events",
    "events": "prefect.cli.events",
    "experimental": "prefect.cli.experimental",
    "flow": "prefect.cli.flow",
    "flows": "prefect.cli.flow",
    "flow-run": "prefect.cli.flow_run",
    "flow-runs": "prefect.cli.flow_run",
    "global-concurrency-limit": "prefect.cli.global_concurrency_limit",
    "gcl": "prefect.cli.global_concurrency_limit",
    "profile": "prefect.cli.profile",
    "profiles": "prefect.cli.profile",
    "sdk": "prefect.cli.sdk",
    "server": "prefect.cli.server",
    "shell": "prefect.cli.shell",
    "task": "prefect.cli.task",
    "task-run": "prefect.cli.task_run",
    "task-runs": "prefect.cli.task_run",
    "transfer": "prefect.cli.transfer",
    "variable": "prefect.cli.variable",
    "work-pool": "prefect.cli.work_pool",
    "work-queue": "prefect.cli.work_queue",
    "work-queues": "prefect.cli.work_queue",
    "worker": "prefect.cli.worker",
    "automation": "prefect.events.cli.automations",
    "automations": "prefect.events.cli.automations",
}

LazyTyperGroup.register_lazy_commands(_LAZY_COMMANDS, typer_instance=app)
