"""Remove flow runners

Revision ID: e085c9cbf8ce
Revises: 0f27d462bf6d
Create Date: 2022-07-21 13:31:34.045385

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "e085c9cbf8ce"
down_revision = "0f27d462bf6d"
branch_labels = None
depends_on = None


def upgrade():
    op.drop_column("deployment", "flow_runner_type")
    op.drop_column("deployment", "flow_runner_config")
    op.drop_column("deployment", "description")
    op.drop_column("flow_run", "flow_runner_type")
    op.drop_column("flow_run", "flow_runner_config")
    op.drop_column("flow_run", "empirical_config")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "flow_run",
        sa.Column(
            "empirical_config",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "flow_run",
        sa.Column(
            "flow_runner_config",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "flow_run",
        sa.Column("flow_runner_type", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "deployment",
        sa.Column("description", sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "deployment",
        sa.Column(
            "flow_runner_config",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "deployment",
        sa.Column("flow_runner_type", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
