query Errors($heartbeat: timestamptz, $flowId: uuid) {
  flow_run(
    where: {
      heartbeat: { _gte: $heartbeat }
      flow: { id: { _eq: $flowId } }
      logs: { level: { _in: ["CRITICAL", "ERROR"] } }
    }
    order_by: [{ heartbeat: desc }]
  ) {
    id
    name
    logs(
      limit: 1
      where: { level: { _in: ["CRITICAL", "ERROR"] }, timestamp: { _gte: $heartbeat } }
    ) {
      id
      level
      message
      name
      timestamp
    }
  }
}
