query Flow($id: uuid!) {
  flow_by_pk(id: $id) {
    id
    name
    description
    created
    archived
    storage
    environment
    parameters
    version
    schedules {
      id
      active
      schedule
      schedule_start
      schedule_end
    }
  }
}
