query TableFlowRunsCount(
  $flowId: uuid
  $name: String
  $heartbeat: timestamptz
) {
  flow_run_aggregate(
    where: {
      flow_id: { _eq: $flowId }
      name: { _ilike: $name }
      heartbeat: { _gte: $heartbeat }
      state: { _neq: "Scheduled" }
    }
  ) {
    aggregate {
      count
    }
  }
}
