query FailureCount($heartbeat: timestamptz) {
  flow_aggregate(
    where: {
      flow_runs: { state: { _eq: "Failed" }, heartbeat: { _gte: $heartbeat } }
    }
  ) {
    aggregate {
      count
    }
  }
}
