query Heartbeat($timestamp: timestamptz, $state: String) {
  flow_run(
    limit: 10
    where: { state_timestamp: { _gte: $timestamp }, state: { _eq: $state } }
    order_by: { state_timestamp: desc_nulls_last }
  ) {
    id
    name
    scheduled_start_time
    state
    state_timestamp
    flow {
      id
      name
    }
  }
}
