query UpcomingFlowRuns {
  flow_run(
    where: { state: { _eq: "Scheduled" } }
    order_by: [{ scheduled_start_time: asc }, { flow: { name: asc } }]
  ) {
    id
    name
    state
    scheduled_start_time
    version
    flow {
      id
      name
    }
    task_runs {
      id
      version
    }
  }
}
