import createClient from "openapi-fetch";
import type { paths } from "./prefect.ts"; // generated by openapi-typescript

// TODO: Make the baseUrl configurable
export const createQueryService = () =>
	createClient<paths>({
		baseUrl: "http://localhost:4200/api",
	});
