query GlobalSearchByName($name: String) {
  flow(where: { name: { _ilike: $name }, archived: { _eq: false } }, limit: 5) {
    id
    name
  }
  flow_run(
    where: { name: { _ilike: $name }, flow: { archived: { _eq: false } } }
    limit: 5
  ) {
    id
    name
    flow {
      id
      name
    }
  }
  task(
    where: { name: { _ilike: $name }, flow: { archived: { _eq: false } } }
    limit: 5
  ) {
    id
    name
    flow {
      id
      name
    }
  }
}
