query GlobalSearchByID($id: uuid!) {
  flow(where: { id: { _eq: $id } }) {
    id
    name
  }
  flow_run(where: { id: { _eq: $id } }) {
    id
    name
    flow {
      id
      name
    }
  }
  task(where: { id: { _eq: $id } }) {
    id
    name
    flow {
      id
      name
    }
  }
  task_run(where: { id: { _eq: $id } }) {
    id
    task {
      id
      name
      flow {
        id
        name
      }
    }
  }
}
