#!/bin/bash
pytest \
    -n auto \
    --maxprocesses 6 \
    --cov-reset \
    --cov=src/prefect/events \
    --cov=src/prefect/server/events \
    --cov=tests/events \
    --no-cov-on-fail \
    --cov-branch \
    --cov-report=term-missing \
    tests/events/ \
    $@
