#!/bin/bash
set -e
docker compose down -v
docker compose up -d test-db

DB_URL=postgresql+asyncpg://prefect:prefect@localhost:15432/orion
PREFECT_ORION_DATABASE_CONNECTION_URL=$DB_URL pytest --exclude-services $@
