query TaskRun($id: uuid!) {
  task_run_by_pk(id: $id) {
    id
    version
    state
    state_message
    state_timestamp
    duration
    heartbeat
    start_time
    end_time
    map_index
    run_count
    serialized_state
    task {
      id
      name
      retry_delay
      max_retries
      trigger
      type

      upstream_edges {
        id
        upstream_task {
          id
          name
          retry_delay
          max_retries
          trigger
          type
        }
      }
      downstream_edges {
        id
        downstream_task {
          id
          name
          retry_delay
          max_retries
          trigger
          type
        }
      }
    }
    flow_run {
      id
      name
      state
      flow {
        id
        name
      }
      parameters
      version
    }
  }
}
